/* Token */
export const SIGNOUT = "SIGNOUT";
export const SIGNUP = "SIGNUP";
export const SIGNIN = "SIGNIN";

/* User */
export const GET_USER = "GET_USER";

/* Loading */
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

/* Products */
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCTS_BY_USER = "FETCH_PRODUCTS_BY_USER";

/* Linksections */
export const FETCH_ALL_LINKSECTIONS = "FETCH_ALL_LINKSECTIONS";
export const CREATE_LINKSECTION = "CREATE_LINKSECTION";
export const UPDATE_LINKSECTION = "UPDATE_LINKSECTION";
export const DELETE_LINKSECTION = "DELETE_LINKSECTION";
export const FETCH_LINKSECTION = "FETCH_LINKSECTION";
export const FETCH_LINKSECTIONS_BY_USER = "FETCH_LINKSECTIONS_BY_USER";

/* Links */
export const FETCH_ALL_LINKS = "FETCH_ALL_LINKS";
export const CREATE_LINK = "CREATE_LINKS";
export const UPDATE_LINK = "UPDATE_LINKS";
export const DELETE_LINK = "DELETE_LINKS";
export const FETCH_LINK = "FETCH_LINK";
export const FETCH_LINKS_BY_LINKSECTION = "FETCH_LINKS_BY_LINKSECTION";
